### ISSUE TITLE
parse json

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/jsonbeans#1]
_From [eoupri...@gmail.com](https://code.google.com/u/104049205593678170799/) on March 20, 2012 10:24:08_

To parse json string to object,if the object have any integer property,will eccour :
==================================================================
Unable to convert value to required type: 31.0 (int)

the reason 
java.lang.NumberFormatException: For input string: "31.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:456)

==================================================================
{numbers:[{type:jery.test.PhoneNumber,name:Home,number:"206-555-1234"},{type:jery.test.PhoneNumber,name:Work,number:"425-555-4321"}],age:31,name:Nate}

_Original issue: http://code.google.com/p/jsonbeans/issues/detail?id=1_

**Comment by NathanSweet** [comment]
No idea, this isn't a proper issue.
