### ISSUE TITLE
How to fetch the latest changes using gradle?

### ISSUE THREAD

**Issue by ThanosFisherman** [EsotericSoftware/jsonbeans#12]
Hey Nate,
Can you let me know how can I fetch your latest changes in android studio using gradle? So far I do it like this:

buildscript {
    repositories {
        jcenter()
    }
dependencies {
    compile 'com.esotericsoftware:jsonbeans:+'
}

But Judging from the dowloaded sources, the latest changes in jsonbeans are not there. Maybe I could fetch this directly from github?
Thanks

**Comment by NathanSweet** [comment]
Sorry, I have never used gradle.

**Comment by ThanosFisherman** [comment]
hm ok thanks then I guess I will do it the traditional way :)

**Comment by NathanSweet** [comment]
Gradle is neat, eg being able to build for ios and Android from the command
line, but there's something to be said about the simplicity of the old way.

**Comment by ThanosFisherman** [comment]
Are the changes you make here pused on maven repo as well? If yes then I won't have to change anything to my gradle script.

**Comment by ThanosFisherman** [comment]
Anyway I try to research this a little bit before I end up to the old way and let you know if you are interested

**Comment by ThanosFisherman** [comment]
Just for the record I was doing it right. Unless the maven central repo is updated with the new jsonbean  changes, I'd have to compile the project the old way.
There are also some plugins for gradle to fetch directly from github source but nah it's too much hassle and they don't always work as expected
So I ended up compiling and including the jsonbeans.jar file in android studio

Cheers
