### ISSUE TITLE
Conversation using Node.js

### ISSUE THREAD

**Issue by touhidurrr** [EsotericSoftware/jsonbeans#16]
I want to parse the exproted minimal Json with Node.js. as expected `JSON.parse` dosn't work. How do I parse it?

**Comment by NathanSweet** [comment]
Use `OutputType.json` when using JsonBeans to write JSON other apps can read.

**Comment by touhidurrr** [comment]
I meant without using `OutputType.json`
Playing a Game that doesn use it.

**Comment by NathanSweet** [comment]
Other apps won't be able to read it then, unless they have very loose JSON parsing. You can read it with jsonbeans and write it out again.
