### ISSUE TITLE
Json.prettyPrint() only supports objects, not arrays

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/jsonbeans#2]
_From [Robert.E...@gmail.com](https://code.google.com/u/106884933612873765651/) on February 23, 2013 17:19:32_

JSON text can either be an object or array for the "top-level" object, but JSON.prettyPrint() only works for objects.  See <a href="http://www.ietf.org/rfc/rfc4627.txt" rel="nofollow">http://www.ietf.org/rfc/rfc4627.txt</a>.&#13;
&#13;
<b>What steps will reproduce the problem?</b>
1. Try to pretty-print something like '[ "one": "value", "bool": true ]'&#13;
2. Get an error&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Expected pretty printing to work, but it didn't.&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
Latest binary build.&#13;

_Original issue: http://code.google.com/p/jsonbeans/issues/detail?id=2_

**Comment by NathanSweet** [comment]
Works with latest.
