### ISSUE TITLE
BSON Support

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/jsonbeans#3]
_From [harry.c...@cloudshards.com](https://code.google.com/u/103605517436890058774/) on May 02, 2013 10:36:58_

Looking to use this with MongoDB. Possible to add BSON support? Thanks.

_Original issue: http://code.google.com/p/jsonbeans/issues/detail?id=3_

**Comment by NathanSweet** [comment]
I don't think so. BSON doesn't make much sense to me, seems there are better formats.
